# LambdaTest Configuration

# Project and folder configuration
project_id: "01M05STEJTV1737263QGB04V3D"
folder_id: "01M05STSKFGAVE8E5CTCJZ1B3Y"

# Test Run configuration
assignee: 41319
environment_id: 266986

# Test URL for automation
# test_url: "https://demo.lambdatestinternal.com"
