# LambdaTest Configuration

# Project and folder configuration
project_id: "01JCQR85K0QZFTSEP5S2EATFEQ"
folder_id: "01JCQR85M5DT1KGAH0BN7S29Z9"

# Test Run configuration
assignee: 1194719
environment_id: 220422

# Test URL for automation
test_url: "https://demo.lambdatestinternal.com"
